apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argoprueba1
  name: argoprueba1
  namespace: argocd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: argoprueba1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: argoprueba1
    spec:
      containers:
      - image: robertorm/pruebatekton:a8d90db
        name: argoprueba1
        resources: {}

