apiVersion: v1
kind: Service
metadata:
  labels:
    app: argoprueba1
  name: argoprueba1
  namespace: argocd
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argoprueba1
